version: '3'
services: 
  scrapper:
    tty: true
    build: scraper
    volumes: 
      - ./scraper:/app/
    environment: 
      DB_URI: "mongodb://db:27017"
  
  db:
    image: mongo
    volumes: 
      - ./db:/data/db
