version: '3'
services:
  api:
    tty: true
    build: api
    environment: 
      DB_URI: "mongodb://db:27017/proyecto"
    depends_on: 
      - db
    ports: 
      - 3000:5000
    volumes:
      - ./api:/app/
  scrapper:
    tty: true
    build: scraper
    volumes: 
      - ./scraper:/app/
    environment: 
      DB_URI: "mongodb://db:27017"
    depends_on: 
      - db
  
  db:
    image: mongo
    volumes: 
      - ./db:/data/db
